### ISSUE TITLE
Display file name in sidebar instead of Home...

### ISSUE THREAD

**Issue by jessegrosjean** [hbsw/tp-issues#139]
Good idea?

**Comment by greghilljr** [comment]
Maybe set in Preferences?

**Comment by jessegrosjean** [comment]
That could be possible, though I think better to avoid preferences for something like this. I'm pretty sure it does make sense (display filename instead of home), just need to try out the implementation first.

**Comment by greghilljr** [comment]
Indeed you're probably right. As it is, I'm kind of migrating over to FT for Atom (which is fantastic, BTW), so my workflow has kind of changed anyway. Do you anticipate adding functionality for managing several files in the same sidebar?

**Comment by jessegrosjean** [comment]
> Do you anticipate adding functionality for managing several files in the same sidebar?

I would like to, but no plans right now. Once TaskPaper 3 is out one option is to port that work back to Atom. And then that functionality would come for free if you were using Atom. So as a user you could choose between TaskPaper 3 the native app, and TaskPaper 3 the Atom plugin. That's just a thought though, not a concrete plan. The big roadblock is I'm not sure I can make enough selling Atom stuff to pay for my time.
