### ISSUE TITLE
bracket-matching glitch in @search

### ISSUE THREAD

**Issue by RobTrew** [hbsw/tp-issues#146]
The parse of itemPaths containing brackets appears to misread where the itemPath ends.

See, for example: @search((@today//* union @today) intersect (not @done))

**Comment by RobTrew** [comment]
or:
@search(//@today//(not @done))

**Comment by jessegrosjean** [comment]
This issue is that tag values cannot include the ")" character. When you need to enter that character in a tag you need to escape it, so instead of typing ")" type "\)". I think that should work around the problem.
