### ISSUE TITLE
Tag parse problem when white-space follows trailling tags ?

### ISSUE THREAD

**Issue by RobTrew** [hbsw/tp-issues#230]
I notice that this line parses correctly when right-trimmed of trailling whitespace:

- To un-indent item s press Shift-Tab. @due(2016-04-17) @late @alpha

but if we add a white space after the @alpha tag, .bodyDisplayString doesn't drop the tags

```
- To un-indent item s press Shift-Tab. @due(2016-04-17) @late @alpha 
```

```javascript
(function () {
    'use strict';

    function TaskPaperContext(editor, options) {

        return editor
            .selection
            .selectedItems
            .map(function (item) {
                return item.bodyDisplayString;
            });
    }

    var ds = Application("TaskPaper")
        .documents,
        d = ds.length ? ds[0] : undefined;

    return d ? d.evaluate({
        script: TaskPaperContext.toString(),
        withOptions: {}
    }) : undefined;

})();
```

-->

```
["To un-indent item s press Shift-Tab. @due(2016-04-17) @late @alpha "]
```

**Comment by jessegrosjean** [comment]
It's a little odd, but I think I'm going to leave this as is for two reasons:

1. TaskPaper does consider a whitespace at the end of a line significant in the case of project syntax. I even suggest added a whitespace after the : as a way to escape project syntax.

2. I don't think its normal to intentionally leave whitespace at the end of the line, so it should always be fixable by just deleting that trailing space.

I guess one takeaway is that bodyDisplayString is generally a somewhat arbitrary and tricky "display" value?

**Comment by RobTrew** [comment]
I see what you mean. 

(I hadn't grasped that final white space signifies)

(I think I may add a `strip inadvertent trailling white space` button somewhere : - )
