### ISSUE TITLE
Serialization of OPML includes indent attribute

### ISSUE THREAD

**Issue by RobTrew** [hbsw/tp-issues#280]
Can't remember whether the inclusion of  indent="1" etc  in the OPML serialization is part of the design. 

Possibly redundant ?

**Comment by jessegrosjean** [comment]
It's redundant in the case of indent="1", though it can have other values
such as indent="2" in which case it's encoding info that can't otherwise be
encoded in OPML. I'll look to skip the base case when encoding.

Jesse
