### ISSUE TITLE
TP Preview (258) on launch alters size/location of previously saved document.

### ISSUE THREAD

**Issue by ccstone** [hbsw/tp-issues#327]

**Comment by ccstone** [comment]
This may be because a blank document was created on launch that was sized and positioned differently than my preference.

**Comment by jessegrosjean** [comment]
Can you try the latest release and see if you still notice the problem? And if so explain it in a little more detail ... windows seem to restore in the correct location for me. Thanks!

**Comment by jessegrosjean** [comment]
Marking this as done as I can't reproduce

**Comment by ccstone** [comment]
Seems to be working correctly in the latest build – TaskPaper 3.5 Preview (269).
