### ISSUE TITLE
Deleting two items in a search also deletes any unshown items between them

### ISSUE THREAD

**Issue by savagerose** [hbsw/tp-issues#360]

**Comment by savagerose** [comment]
1. Create a document as follows:
test:
	- testa @1
	- testb
	- testc @1
2. Search for @1
3. Delete both items tagged @1
4. Stop searching. All tasks are deleted. Expected behavior is that only the tasks tagged @1 are deleted.

I was able to reproduce this in both v3.3.2 and v3.5. This bug does not seem to occur if the tasks are not in a project.

Thanks! :)

**Comment by jessegrosjean** [comment]
Please see TaskPaper 3.7 Preview, I think it addresses this issue as part of a bigger set of changes to how selection of hidden items works:

http://support.hogbaysoftware.com/t/taskpaper-3-7-preview-291/2905
